config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :visits
  resources :event_occurrences
  resources :event_organizers
  resources :users

  devise_for :users
  # resources :building_accounts
  resources :addresses
  resources :group_contacts
  resources :event_guests
  resources :events
  resources :contacts
  resources :buildings, shallow: true do
    resources :visitor_types
    resources :floors, shallow: true do
      resources :spaces, shallow: true do
        resources :leases
      end
    end
  end
  resources :groups
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/visit.rb
# frozen_string_literal: true

# Join table of EventOccurrence and the guest, along with other attributes.
class Visit < ApplicationRecord
  belongs_to :event_occurrence
  belongs_to :contact
  belongs_to :guest, class_name: 'Contact', foreign_key: 'contact_id' # alias

  belongs_to :checked_in_by_user, class_name: 'User', optional: true
  belongs_to :checked_out_by_user, class_name: 'User', optional: true

  has_one :event, through: :event_occurrence

  validates :event_occurrence, :contact, presence: true
  belongs_to :barcode_disabled_by_user, class_name: 'User', optional: true

  state_machine :state, initial: :scheduled do
    before_transition on: :reset, do: :reset_visit
    before_transition on: :check_in, do: ->(visit) { visit.checked_in_at ||= DateTime.now }
    before_transition on: :check_out, do: ->(visit) { visit.checked_out_at = DateTime.now }
    event :check_in do
      transition scheduled: :checked_in, if: :can_check_in?
    end
    event :check_out do
      transition %i[scheduled checked_in] => :checked_out
    end
    event :reset do
      transition any => :scheduled
    end
  end

  private

  def can_check_in?
    return true if checked_in_by_user.present?

    errors.add(:checked_in_by_user, 'must be present to check in.')
    false
  end

  def can_check_out?
    checked_out_by_user.present?

    errors.add(:checked_out_by_user, 'must be present to check out.')
  end

  def reset_visit
    self.checked_in_at = nil
    self.checked_in_by_user = nil
    self.checked_out_at = nil
    self.checked_out_by_user = nil
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: %i[ show edit update destroy ]

  # GET /visits or /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1 or /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits or /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to visit_url(@visit), notice: "Visit was successfully created." }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1 or /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to visit_url(@visit), notice: "Visit was successfully updated." }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1 or /visits/1.json
  def destroy
    @visit.destroy!

    respond_to do |format|
      format.html { redirect_to visits_url, notice: "Visit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visit_params
      params.require(:visit).permit(:event_occurrence_id, :contact_id, :checked_in_at, :checked_out_at, :checked_in_by_user, :checked_out_by_user, :state, :barcode, :notes, :barcode_disabled_by_user_id, :barcode_disabled_at, :barcode_disabled)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_with(model: visit) do |form| %>
  <% if visit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
        <% visit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :event_occurrence_id, style: "display: block" %>
    <%= form.text_field :event_occurrence_id %>
  </div>

  <div>
    <%= form.label :contact_id, style: "display: block" %>
    <%= form.text_field :contact_id %>
  </div>

  <div>
    <%= form.label :checked_in_at, style: "display: block" %>
    <%= form.datetime_field :checked_in_at %>
  </div>

  <div>
    <%= form.label :checked_out_at, style: "display: block" %>
    <%= form.datetime_field :checked_out_at %>
  </div>

  <div>
    <%= form.label :checked_in_by_user, style: "display: block" %>
    <%= form.datetime_field :checked_in_by_user %>
  </div>

  <div>
    <%= form.label :checked_out_by_user, style: "display: block" %>
    <%= form.datetime_field :checked_out_by_user %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :barcode, style: "display: block" %>
    <%= form.text_field :barcode %>
  </div>

  <div>
    <%= form.label :notes, style: "display: block" %>
    <%= form.text_area :notes %>
  </div>

  <div>
    <%= form.label :barcode_disabled_by_user_id, style: "display: block" %>
    <%= form.text_field :barcode_disabled_by_user_id %>
  </div>

  <div>
    <%= form.label :barcode_disabled_at, style: "display: block" %>
    <%= form.datetime_field :barcode_disabled_at %>
  </div>

  <div>
    <%= form.label :barcode_disabled, style: "display: block" %>
    <%= form.check_box :barcode_disabled %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/visits/_visit.html.erb
<div id="<%= dom_id visit %>">
  <p>
    <strong>Event occurrence:</strong>
    <%= visit.event_occurrence_id %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= visit.contact_id %>
  </p>

  <p>
    <strong>Checked in at:</strong>
    <%= visit.checked_in_at %>
  </p>

  <p>
    <strong>Checked out at:</strong>
    <%= visit.checked_out_at %>
  </p>

  <p>
    <strong>Checked in by user:</strong>
    <%= visit.checked_in_by_user %>
  </p>

  <p>
    <strong>Checked out by user:</strong>
    <%= visit.checked_out_by_user %>
  </p>

  <p>
    <strong>State:</strong>
    <%= visit.state %>
  </p>

  <p>
    <strong>Barcode:</strong>
    <%= visit.barcode %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= visit.notes %>
  </p>

  <p>
    <strong>Barcode disabled by user:</strong>
    <%= visit.barcode_disabled_by_user_id %>
  </p>

  <p>
    <strong>Barcode disabled at:</strong>
    <%= visit.barcode_disabled_at %>
  </p>

  <p>
    <strong>Barcode disabled:</strong>
    <%= visit.barcode_disabled %>
  </p>

</div>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render "form", visit: @visit %>

<br>

<div>
  <%= link_to "Show this visit", @visit %> |
  <%= link_to "Back to visits", visits_path %>
</div>

app/views/visits/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Visits</h1>

<div id="visits">
  <% @visits.each do |visit| %>
    <%= render visit %>
    <p>
      <%= link_to "Show this visit", visit %>
    </p>
  <% end %>
</div>

<%= link_to "New visit", new_visit_path %>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render "form", visit: @visit %>

<br>

<div>
  <%= link_to "Back to visits", visits_path %>
</div>

app/views/visits/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @visit %>

<div>
  <%= link_to "Edit this visit", edit_visit_path(@visit) %> |
  <%= link_to "Back to visits", visits_path %>

  <%= button_to "Destroy this visit", @visit, method: :delete %>
</div>