config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :visits
  resources :event_occurrences
  resources :event_organizers
  resources :users

  devise_for :users
  # resources :building_accounts
  resources :addresses
  resources :group_contacts
  resources :event_guests
  resources :events
  resources :contacts
  resources :buildings, shallow: true do
    resources :visitor_types
    resources :floors, shallow: true do
      resources :spaces, shallow: true do
        resources :leases
      end
    end
  end
  resources :groups
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/group_contact.rb
# frozen_string_literal: true

# Join table to keep track of previous contacts for an existing group.
class GroupContact < ApplicationRecord
  belongs_to :group
  belongs_to :contact
end

app/controllers/group_contacts_controller.rb
class GroupContactsController < ApplicationController
  before_action :set_group_contact, only: %i[ show edit update destroy ]

  # GET /group_contacts or /group_contacts.json
  def index
    @group_contacts = GroupContact.all
  end

  # GET /group_contacts/1 or /group_contacts/1.json
  def show
  end

  # GET /group_contacts/new
  def new
    @group_contact = GroupContact.new
  end

  # GET /group_contacts/1/edit
  def edit
  end

  # POST /group_contacts or /group_contacts.json
  def create
    @group_contact = GroupContact.new(group_contact_params)

    respond_to do |format|
      if @group_contact.save
        format.html { redirect_to group_contact_url(@group_contact), notice: "Group contact was successfully created." }
        format.json { render :show, status: :created, location: @group_contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_contacts/1 or /group_contacts/1.json
  def update
    respond_to do |format|
      if @group_contact.update(group_contact_params)
        format.html { redirect_to group_contact_url(@group_contact), notice: "Group contact was successfully updated." }
        format.json { render :show, status: :ok, location: @group_contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_contacts/1 or /group_contacts/1.json
  def destroy
    @group_contact.destroy!

    respond_to do |format|
      format.html { redirect_to group_contacts_url, notice: "Group contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_contact
      @group_contact = GroupContact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_contact_params
      params.require(:group_contact).permit(:group_id, :contact_id)
    end
end

app/helpers/group_contacts_helper.rb
module GroupContactsHelper
end

app/views/group_contacts/_form.html.erb
<%= form_with(model: group_contact) do |form| %>
  <% if group_contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group_contact.errors.count, "error") %> prohibited this group_contact from being saved:</h2>

      <ul>
        <% group_contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :group_id, style: "display: block" %>
    <%= form.text_field :group_id %>
  </div>

  <div>
    <%= form.label :contact_id, style: "display: block" %>
    <%= form.text_field :contact_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/group_contacts/_group_contact.html.erb
<div id="<%= dom_id group_contact %>">
  <p>
    <strong>Group:</strong>
    <%= group_contact.group_id %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= group_contact.contact_id %>
  </p>

</div>

app/views/group_contacts/edit.html.erb
<h1>Editing group contact</h1>

<%= render "form", group_contact: @group_contact %>

<br>

<div>
  <%= link_to "Show this group contact", @group_contact %> |
  <%= link_to "Back to group contacts", group_contacts_path %>
</div>

app/views/group_contacts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Group contacts</h1>

<div id="group_contacts">
  <% @group_contacts.each do |group_contact| %>
    <%= render group_contact %>
    <p>
      <%= link_to "Show this group contact", group_contact %>
    </p>
  <% end %>
</div>

<%= link_to "New group contact", new_group_contact_path %>

app/views/group_contacts/new.html.erb
<h1>New group contact</h1>

<%= render "form", group_contact: @group_contact %>

<br>

<div>
  <%= link_to "Back to group contacts", group_contacts_path %>
</div>

app/views/group_contacts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group_contact %>

<div>
  <%= link_to "Edit this group contact", edit_group_contact_path(@group_contact) %> |
  <%= link_to "Back to group contacts", group_contacts_path %>

  <%= button_to "Destroy this group contact", @group_contact, method: :delete %>
</div>