config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :visits
  resources :event_occurrences
  resources :event_organizers
  resources :users

  devise_for :users
  # resources :building_accounts
  resources :addresses
  resources :group_contacts
  resources :event_guests
  resources :events
  resources :contacts
  resources :buildings, shallow: true do
    resources :visitor_types
    resources :floors, shallow: true do
      resources :spaces, shallow: true do
        resources :leases
      end
    end
  end
  resources :groups
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/visitor_types_controller.rb
# frozen_string_literal: true

# vt
class VisitorTypesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_building, only: %i[index create]
  before_action :set_visitor_type, only: %i[show update destroy]

  # GET /visitor_types or /visitor_types.json
  def index
    authorize @building, :show?
    @floors = @building.visitor_types
  end

  # GET /visitor_types/1 or /visitor_types/1.json
  def show
    authorize @visitor_type.building
  end

  # POST /visitor_types or /visitor_types.json
  def create
    authorize @building, :show?
    @visitor_type = VisitorType.new(visitor_type_params)
    @visitor_type.building = @building

    if @visitor_type.save
      render :show, status: :created, location: @visitor_type
    else
      render json: @visitor_type.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /visitor_types/1 or /visitor_types/1.json
  def update
    authorize @visitor_type.building
    if @visitor_type.update(visitor_type_params)
      render :show, status: :ok, location: @visitor_type
    else
      render json: @visitor_type.errors, status: :unprocessable_entity
    end
  end

  # DELETE /visitor_types/1 or /visitor_types/1.json
  def destroy
    authorize @visitor_type.building, :show?
    @visitor_type.destroy!

    render(json: { notice: 'Visitor Type was successfully destroyed.' })
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_visitor_type
    @visitor_type = VisitorType.find(params[:id])
  end

  def set_building
    @building = Building.find(params[:building_id])
    # TODO: Break if floor not part of building
  end

  # Only allow a list of trusted parameters through.
  def visitor_type_params
    params.require(:visitor_type).permit(:name, :category, :hide_barcode)
  end
end

app/helpers/visitor_types_helper.rb
module VisitorTypesHelper
end

app/views/visitor_types/_form.html.erb
<%= form_with(model: visitor_type) do |form| %>
  <% if visitor_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(visitor_type.errors.count, "error") %> prohibited this visitor_type from being saved:</h2>

      <ul>
        <% visitor_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :building_id, style: "display: block" %>
    <%= form.text_field :building_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :hide_barcode, style: "display: block" %>
    <%= form.check_box :hide_barcode %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/visitor_types/_visitor_type.html.erb
<div id="<%= dom_id visitor_type %>">
  <p>
    <strong>Building:</strong>
    <%= visitor_type.building_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= visitor_type.name %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= visitor_type.category %>
  </p>

  <p>
    <strong>Hide barcode:</strong>
    <%= visitor_type.hide_barcode %>
  </p>

</div>

app/views/visitor_types/edit.html.erb
<h1>Editing visitor type</h1>

<%= render "form", visitor_type: @visitor_type %>

<br>

<div>
  <%= link_to "Show this visitor type", @visitor_type %> |
  <%= link_to "Back to visitor types", visitor_types_path %>
</div>

app/views/visitor_types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Visitor types</h1>

<div id="visitor_types">
  <% @visitor_types.each do |visitor_type| %>
    <%= render visitor_type %>
    <p>
      <%= link_to "Show this visitor type", visitor_type %>
    </p>
  <% end %>
</div>

<%= link_to "New visitor type", new_visitor_type_path %>

app/views/visitor_types/new.html.erb
<h1>New visitor type</h1>

<%= render "form", visitor_type: @visitor_type %>

<br>

<div>
  <%= link_to "Back to visitor types", visitor_types_path %>
</div>

app/views/visitor_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @visitor_type %>

<div>
  <%= link_to "Edit this visitor type", edit_visitor_type_path(@visitor_type) %> |
  <%= link_to "Back to visitor types", visitor_types_path %>

  <%= button_to "Destroy this visitor type", @visitor_type, method: :delete %>
</div>